site_name: Bedrock Swarm
site_description: A framework for building multi-agent systems using Amazon Bedrock
repo_url: https://github.com/sandrich/bedrock-swarm
repo_name: bedrock-swarm

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# extra_javascript:
#   - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js

plugins:
  - search
  - mermaid2:
      version: 10.4.0
      arguments:
        securityLevel: 'loose'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/bedrock_swarm]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_submodules: true
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            show_if_no_docstring: false
            show_signature_annotations: false
            extra:
              show_warnings: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - footnotes

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quickstart.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Architecture:
    - Overview: concepts/architecture.md
    - Communication Flow: concepts/communication.md
    - Event System: concepts/events.md
  - Core Concepts:
    - Agency: concepts/agency.md
    - Coordinator: concepts/coordinator.md
    - Specialists: concepts/specialists.md
    - Tools: concepts/tools.md
    - Memory: concepts/memory.md
    - Threads: concepts/threads.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Calculator Example: examples/calculator.md
    - Time Expert Example: examples/time.md
    - Multi-Agent Example: examples/multi-agent.md
  - API Reference:
    - Agency: api/agency.md
    - Agents: api/agents.md
    - Tools: api/tools.md
    - Events: api/events.md
    - Memory: api/memory.md
  - Contributing: contributing.md
