site_name: Bedrock Swarm
site_description: A framework for building multi-agent systems using Amazon Bedrock
repo_url: https://github.com/sandrich/bedrock-swarm
repo_name: bedrock-swarm
strict: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# extra_javascript:
#   - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js

plugins:
  - search
  - mermaid2:
      version: 10.4.0
      arguments:
        securityLevel: 'loose'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/bedrock_swarm]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_submodules: true
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            show_if_no_docstring: false
            show_signature_annotations: true
            show_bases: true
            members_order: source
            docstring_options:
              ignore_init_summary: true
            extra:
              show_warnings: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - md_in_html
  - def_list

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quickstart.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Architecture:
    - Overview: concepts/architecture.md
    - Communication Flow: concepts/communication.md
    - Event System: concepts/events.md
  - Core Concepts:
    - Agency: concepts/agency.md
    - Agents: concepts/agents.md
    - Models: concepts/models.md
    - Tools: concepts/tools.md
    - Memory: concepts/memory.md
    - Threads: concepts/threads.md
    - Events: concepts/events.md
    - Coordinator: concepts/coordinator.md
    - Specialists: concepts/specialists.md
  - Examples:
    - Overview: examples/index.md
    - Basic Usage: examples/basic.md
    - Calculator Example: examples/calculator.md
    - Time Expert Example: examples/time.md
    - Multi-Agent Example: examples/multi-agent.md
  - API Reference:
    - Overview: api/index.md
    - Agency:
      - Overview: api/agency/index.md
      - Agency API: api/agency.md
      - Thread: api/agency/thread.md
      - Run: api/agency/run.md
      - Events: api/agency/events.md
      - Agents: api/agency/agents.md
      - Base Agent: api/agents/base.md
    - Models:
      - Overview: api/models/index.md
      - Base Model: api/models/base.md
      - Titan Model: api/models/titan.md
      - Claude Model: api/models/claude.md
      - Model Factory: api/models/factory.md
    - Tools:
      - Overview: api/tools/index.md
      - API Reference: api/tools.md
      - Base Tool: api/tools/base.md
      - Calculator: api/tools/calculator.md
      - Time: api/tools/time.md
      - Send Message: api/tools/send_message.md
      - Validation: api/tools/validation.md
  - Development:
    - Overview: development/index.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Code Organization: development/organization.md
    - Tool Development: development/tools.md
  - Code of Conduct: code_of_conduct.md
