site_name: Bedrock Swarm
site_description: A framework for building multi-agent systems using AWS Bedrock
repo_url: https://github.com/yourusername/bedrock-swarm
repo_name: bedrock-swarm

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js

plugins:
  - search
  - mermaid2:
      version: 10.4.0
      arguments:
        securityLevel: 'loose'
        theme: default
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/bedrock_swarm]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_submodules: true
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            show_if_no_docstring: false
            show_signature_annotations: false
            extra:
              show_warnings: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Concepts:
    - Agency: concepts/agency.md
    - Agents: concepts/agents.md
    - Tools: concepts/tools.md
    - Threads: concepts/threads.md
    - Memory: concepts/memory.md
    - Events: concepts/events.md
  - Examples: examples/index.md
