name: Release and Publish

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    
    # Add permissions needed for OIDC
    permissions:
      id-token: write  # Required for OIDC
      contents: write  # Required for gh-pages
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install ".[dev,docs]"
        
    - name: Build package
      run: |
        python -m build
        
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        verbose: true
        print-hash: true  # Print package hash for verification
        
    - name: Build documentation
      run: |
        mkdocs build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        
    - name: Trigger ReadTheDocs build
      uses: dfm/rtds-action@v1
      with:
        webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
        webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
        commit_ref: ${{ github.ref }} 